// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package gotrue

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type CustomOauthProvider struct {
	pulumi.CustomResourceState

	AcceptableClientIds pulumi.StringArrayOutput `pulumi:"acceptableClientIds"`
	AttributeMapping    pulumi.StringPtrOutput   `pulumi:"attributeMapping"`
	AuthorizationParams pulumi.StringPtrOutput   `pulumi:"authorizationParams"`
	AuthorizationUrl    pulumi.StringPtrOutput   `pulumi:"authorizationUrl"`
	ClientId            pulumi.StringOutput      `pulumi:"clientId"`
	ClientSecret        pulumi.StringOutput      `pulumi:"clientSecret"`
	CreatedAt           pulumi.StringOutput      `pulumi:"createdAt"`
	DiscoveryDocument   pulumi.StringOutput      `pulumi:"discoveryDocument"`
	DiscoveryUrl        pulumi.StringPtrOutput   `pulumi:"discoveryUrl"`
	EmailOptional       pulumi.BoolOutput        `pulumi:"emailOptional"`
	Enabled             pulumi.BoolOutput        `pulumi:"enabled"`
	Identifier          pulumi.StringOutput      `pulumi:"identifier"`
	Issuer              pulumi.StringPtrOutput   `pulumi:"issuer"`
	JwksUri             pulumi.StringPtrOutput   `pulumi:"jwksUri"`
	Name                pulumi.StringOutput      `pulumi:"name"`
	PkceEnabled         pulumi.BoolOutput        `pulumi:"pkceEnabled"`
	ProviderType        pulumi.StringOutput      `pulumi:"providerType"`
	Scopes              pulumi.StringArrayOutput `pulumi:"scopes"`
	SkipNonceCheck      pulumi.BoolOutput        `pulumi:"skipNonceCheck"`
	TokenUrl            pulumi.StringPtrOutput   `pulumi:"tokenUrl"`
	UpdatedAt           pulumi.StringOutput      `pulumi:"updatedAt"`
	UserinfoUrl         pulumi.StringPtrOutput   `pulumi:"userinfoUrl"`
}

// NewCustomOauthProvider registers a new resource with the given unique name, arguments, and options.
func NewCustomOauthProvider(ctx *pulumi.Context,
	name string, args *CustomOauthProviderArgs, opts ...pulumi.ResourceOption) (*CustomOauthProvider, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClientId == nil {
		return nil, errors.New("invalid value for required argument 'ClientId'")
	}
	if args.ClientSecret == nil {
		return nil, errors.New("invalid value for required argument 'ClientSecret'")
	}
	if args.Identifier == nil {
		return nil, errors.New("invalid value for required argument 'Identifier'")
	}
	if args.ProviderType == nil {
		return nil, errors.New("invalid value for required argument 'ProviderType'")
	}
	if args.ClientSecret != nil {
		args.ClientSecret = pulumi.ToSecret(args.ClientSecret).(pulumi.StringOutput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"clientSecret",
	})
	opts = append(opts, secrets)
	opts = pkgResourceDefaultOpts(opts)
	var resource CustomOauthProvider
	err := ctx.RegisterResource("gotrue:index/customOauthProvider:CustomOauthProvider", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCustomOauthProvider gets an existing CustomOauthProvider resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCustomOauthProvider(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CustomOauthProviderState, opts ...pulumi.ResourceOption) (*CustomOauthProvider, error) {
	var resource CustomOauthProvider
	err := ctx.ReadResource("gotrue:index/customOauthProvider:CustomOauthProvider", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CustomOauthProvider resources.
type customOauthProviderState struct {
	AcceptableClientIds []string `pulumi:"acceptableClientIds"`
	AttributeMapping    *string  `pulumi:"attributeMapping"`
	AuthorizationParams *string  `pulumi:"authorizationParams"`
	AuthorizationUrl    *string  `pulumi:"authorizationUrl"`
	ClientId            *string  `pulumi:"clientId"`
	ClientSecret        *string  `pulumi:"clientSecret"`
	CreatedAt           *string  `pulumi:"createdAt"`
	DiscoveryDocument   *string  `pulumi:"discoveryDocument"`
	DiscoveryUrl        *string  `pulumi:"discoveryUrl"`
	EmailOptional       *bool    `pulumi:"emailOptional"`
	Enabled             *bool    `pulumi:"enabled"`
	Identifier          *string  `pulumi:"identifier"`
	Issuer              *string  `pulumi:"issuer"`
	JwksUri             *string  `pulumi:"jwksUri"`
	Name                *string  `pulumi:"name"`
	PkceEnabled         *bool    `pulumi:"pkceEnabled"`
	ProviderType        *string  `pulumi:"providerType"`
	Scopes              []string `pulumi:"scopes"`
	SkipNonceCheck      *bool    `pulumi:"skipNonceCheck"`
	TokenUrl            *string  `pulumi:"tokenUrl"`
	UpdatedAt           *string  `pulumi:"updatedAt"`
	UserinfoUrl         *string  `pulumi:"userinfoUrl"`
}

type CustomOauthProviderState struct {
	AcceptableClientIds pulumi.StringArrayInput
	AttributeMapping    pulumi.StringPtrInput
	AuthorizationParams pulumi.StringPtrInput
	AuthorizationUrl    pulumi.StringPtrInput
	ClientId            pulumi.StringPtrInput
	ClientSecret        pulumi.StringPtrInput
	CreatedAt           pulumi.StringPtrInput
	DiscoveryDocument   pulumi.StringPtrInput
	DiscoveryUrl        pulumi.StringPtrInput
	EmailOptional       pulumi.BoolPtrInput
	Enabled             pulumi.BoolPtrInput
	Identifier          pulumi.StringPtrInput
	Issuer              pulumi.StringPtrInput
	JwksUri             pulumi.StringPtrInput
	Name                pulumi.StringPtrInput
	PkceEnabled         pulumi.BoolPtrInput
	ProviderType        pulumi.StringPtrInput
	Scopes              pulumi.StringArrayInput
	SkipNonceCheck      pulumi.BoolPtrInput
	TokenUrl            pulumi.StringPtrInput
	UpdatedAt           pulumi.StringPtrInput
	UserinfoUrl         pulumi.StringPtrInput
}

func (CustomOauthProviderState) ElementType() reflect.Type {
	return reflect.TypeOf((*customOauthProviderState)(nil)).Elem()
}

type customOauthProviderArgs struct {
	AcceptableClientIds []string `pulumi:"acceptableClientIds"`
	AttributeMapping    *string  `pulumi:"attributeMapping"`
	AuthorizationParams *string  `pulumi:"authorizationParams"`
	AuthorizationUrl    *string  `pulumi:"authorizationUrl"`
	ClientId            string   `pulumi:"clientId"`
	ClientSecret        string   `pulumi:"clientSecret"`
	DiscoveryUrl        *string  `pulumi:"discoveryUrl"`
	EmailOptional       *bool    `pulumi:"emailOptional"`
	Enabled             *bool    `pulumi:"enabled"`
	Identifier          string   `pulumi:"identifier"`
	Issuer              *string  `pulumi:"issuer"`
	JwksUri             *string  `pulumi:"jwksUri"`
	Name                *string  `pulumi:"name"`
	PkceEnabled         *bool    `pulumi:"pkceEnabled"`
	ProviderType        string   `pulumi:"providerType"`
	Scopes              []string `pulumi:"scopes"`
	SkipNonceCheck      *bool    `pulumi:"skipNonceCheck"`
	TokenUrl            *string  `pulumi:"tokenUrl"`
	UserinfoUrl         *string  `pulumi:"userinfoUrl"`
}

// The set of arguments for constructing a CustomOauthProvider resource.
type CustomOauthProviderArgs struct {
	AcceptableClientIds pulumi.StringArrayInput
	AttributeMapping    pulumi.StringPtrInput
	AuthorizationParams pulumi.StringPtrInput
	AuthorizationUrl    pulumi.StringPtrInput
	ClientId            pulumi.StringInput
	ClientSecret        pulumi.StringInput
	DiscoveryUrl        pulumi.StringPtrInput
	EmailOptional       pulumi.BoolPtrInput
	Enabled             pulumi.BoolPtrInput
	Identifier          pulumi.StringInput
	Issuer              pulumi.StringPtrInput
	JwksUri             pulumi.StringPtrInput
	Name                pulumi.StringPtrInput
	PkceEnabled         pulumi.BoolPtrInput
	ProviderType        pulumi.StringInput
	Scopes              pulumi.StringArrayInput
	SkipNonceCheck      pulumi.BoolPtrInput
	TokenUrl            pulumi.StringPtrInput
	UserinfoUrl         pulumi.StringPtrInput
}

func (CustomOauthProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*customOauthProviderArgs)(nil)).Elem()
}

type CustomOauthProviderInput interface {
	pulumi.Input

	ToCustomOauthProviderOutput() CustomOauthProviderOutput
	ToCustomOauthProviderOutputWithContext(ctx context.Context) CustomOauthProviderOutput
}

func (*CustomOauthProvider) ElementType() reflect.Type {
	return reflect.TypeOf((**CustomOauthProvider)(nil)).Elem()
}

func (i *CustomOauthProvider) ToCustomOauthProviderOutput() CustomOauthProviderOutput {
	return i.ToCustomOauthProviderOutputWithContext(context.Background())
}

func (i *CustomOauthProvider) ToCustomOauthProviderOutputWithContext(ctx context.Context) CustomOauthProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CustomOauthProviderOutput)
}

// CustomOauthProviderArrayInput is an input type that accepts CustomOauthProviderArray and CustomOauthProviderArrayOutput values.
// You can construct a concrete instance of `CustomOauthProviderArrayInput` via:
//
//	CustomOauthProviderArray{ CustomOauthProviderArgs{...} }
type CustomOauthProviderArrayInput interface {
	pulumi.Input

	ToCustomOauthProviderArrayOutput() CustomOauthProviderArrayOutput
	ToCustomOauthProviderArrayOutputWithContext(context.Context) CustomOauthProviderArrayOutput
}

type CustomOauthProviderArray []CustomOauthProviderInput

func (CustomOauthProviderArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CustomOauthProvider)(nil)).Elem()
}

func (i CustomOauthProviderArray) ToCustomOauthProviderArrayOutput() CustomOauthProviderArrayOutput {
	return i.ToCustomOauthProviderArrayOutputWithContext(context.Background())
}

func (i CustomOauthProviderArray) ToCustomOauthProviderArrayOutputWithContext(ctx context.Context) CustomOauthProviderArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CustomOauthProviderArrayOutput)
}

// CustomOauthProviderMapInput is an input type that accepts CustomOauthProviderMap and CustomOauthProviderMapOutput values.
// You can construct a concrete instance of `CustomOauthProviderMapInput` via:
//
//	CustomOauthProviderMap{ "key": CustomOauthProviderArgs{...} }
type CustomOauthProviderMapInput interface {
	pulumi.Input

	ToCustomOauthProviderMapOutput() CustomOauthProviderMapOutput
	ToCustomOauthProviderMapOutputWithContext(context.Context) CustomOauthProviderMapOutput
}

type CustomOauthProviderMap map[string]CustomOauthProviderInput

func (CustomOauthProviderMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CustomOauthProvider)(nil)).Elem()
}

func (i CustomOauthProviderMap) ToCustomOauthProviderMapOutput() CustomOauthProviderMapOutput {
	return i.ToCustomOauthProviderMapOutputWithContext(context.Background())
}

func (i CustomOauthProviderMap) ToCustomOauthProviderMapOutputWithContext(ctx context.Context) CustomOauthProviderMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CustomOauthProviderMapOutput)
}

type CustomOauthProviderOutput struct{ *pulumi.OutputState }

func (CustomOauthProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CustomOauthProvider)(nil)).Elem()
}

func (o CustomOauthProviderOutput) ToCustomOauthProviderOutput() CustomOauthProviderOutput {
	return o
}

func (o CustomOauthProviderOutput) ToCustomOauthProviderOutputWithContext(ctx context.Context) CustomOauthProviderOutput {
	return o
}

func (o CustomOauthProviderOutput) AcceptableClientIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *CustomOauthProvider) pulumi.StringArrayOutput { return v.AcceptableClientIds }).(pulumi.StringArrayOutput)
}

func (o CustomOauthProviderOutput) AttributeMapping() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CustomOauthProvider) pulumi.StringPtrOutput { return v.AttributeMapping }).(pulumi.StringPtrOutput)
}

func (o CustomOauthProviderOutput) AuthorizationParams() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CustomOauthProvider) pulumi.StringPtrOutput { return v.AuthorizationParams }).(pulumi.StringPtrOutput)
}

func (o CustomOauthProviderOutput) AuthorizationUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CustomOauthProvider) pulumi.StringPtrOutput { return v.AuthorizationUrl }).(pulumi.StringPtrOutput)
}

func (o CustomOauthProviderOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *CustomOauthProvider) pulumi.StringOutput { return v.ClientId }).(pulumi.StringOutput)
}

func (o CustomOauthProviderOutput) ClientSecret() pulumi.StringOutput {
	return o.ApplyT(func(v *CustomOauthProvider) pulumi.StringOutput { return v.ClientSecret }).(pulumi.StringOutput)
}

func (o CustomOauthProviderOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *CustomOauthProvider) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o CustomOauthProviderOutput) DiscoveryDocument() pulumi.StringOutput {
	return o.ApplyT(func(v *CustomOauthProvider) pulumi.StringOutput { return v.DiscoveryDocument }).(pulumi.StringOutput)
}

func (o CustomOauthProviderOutput) DiscoveryUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CustomOauthProvider) pulumi.StringPtrOutput { return v.DiscoveryUrl }).(pulumi.StringPtrOutput)
}

func (o CustomOauthProviderOutput) EmailOptional() pulumi.BoolOutput {
	return o.ApplyT(func(v *CustomOauthProvider) pulumi.BoolOutput { return v.EmailOptional }).(pulumi.BoolOutput)
}

func (o CustomOauthProviderOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *CustomOauthProvider) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

func (o CustomOauthProviderOutput) Identifier() pulumi.StringOutput {
	return o.ApplyT(func(v *CustomOauthProvider) pulumi.StringOutput { return v.Identifier }).(pulumi.StringOutput)
}

func (o CustomOauthProviderOutput) Issuer() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CustomOauthProvider) pulumi.StringPtrOutput { return v.Issuer }).(pulumi.StringPtrOutput)
}

func (o CustomOauthProviderOutput) JwksUri() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CustomOauthProvider) pulumi.StringPtrOutput { return v.JwksUri }).(pulumi.StringPtrOutput)
}

func (o CustomOauthProviderOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *CustomOauthProvider) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o CustomOauthProviderOutput) PkceEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *CustomOauthProvider) pulumi.BoolOutput { return v.PkceEnabled }).(pulumi.BoolOutput)
}

func (o CustomOauthProviderOutput) ProviderType() pulumi.StringOutput {
	return o.ApplyT(func(v *CustomOauthProvider) pulumi.StringOutput { return v.ProviderType }).(pulumi.StringOutput)
}

func (o CustomOauthProviderOutput) Scopes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *CustomOauthProvider) pulumi.StringArrayOutput { return v.Scopes }).(pulumi.StringArrayOutput)
}

func (o CustomOauthProviderOutput) SkipNonceCheck() pulumi.BoolOutput {
	return o.ApplyT(func(v *CustomOauthProvider) pulumi.BoolOutput { return v.SkipNonceCheck }).(pulumi.BoolOutput)
}

func (o CustomOauthProviderOutput) TokenUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CustomOauthProvider) pulumi.StringPtrOutput { return v.TokenUrl }).(pulumi.StringPtrOutput)
}

func (o CustomOauthProviderOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *CustomOauthProvider) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

func (o CustomOauthProviderOutput) UserinfoUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CustomOauthProvider) pulumi.StringPtrOutput { return v.UserinfoUrl }).(pulumi.StringPtrOutput)
}

type CustomOauthProviderArrayOutput struct{ *pulumi.OutputState }

func (CustomOauthProviderArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CustomOauthProvider)(nil)).Elem()
}

func (o CustomOauthProviderArrayOutput) ToCustomOauthProviderArrayOutput() CustomOauthProviderArrayOutput {
	return o
}

func (o CustomOauthProviderArrayOutput) ToCustomOauthProviderArrayOutputWithContext(ctx context.Context) CustomOauthProviderArrayOutput {
	return o
}

func (o CustomOauthProviderArrayOutput) Index(i pulumi.IntInput) CustomOauthProviderOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *CustomOauthProvider {
		return vs[0].([]*CustomOauthProvider)[vs[1].(int)]
	}).(CustomOauthProviderOutput)
}

type CustomOauthProviderMapOutput struct{ *pulumi.OutputState }

func (CustomOauthProviderMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CustomOauthProvider)(nil)).Elem()
}

func (o CustomOauthProviderMapOutput) ToCustomOauthProviderMapOutput() CustomOauthProviderMapOutput {
	return o
}

func (o CustomOauthProviderMapOutput) ToCustomOauthProviderMapOutputWithContext(ctx context.Context) CustomOauthProviderMapOutput {
	return o
}

func (o CustomOauthProviderMapOutput) MapIndex(k pulumi.StringInput) CustomOauthProviderOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *CustomOauthProvider {
		return vs[0].(map[string]*CustomOauthProvider)[vs[1].(string)]
	}).(CustomOauthProviderOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CustomOauthProviderInput)(nil)).Elem(), &CustomOauthProvider{})
	pulumi.RegisterInputType(reflect.TypeOf((*CustomOauthProviderArrayInput)(nil)).Elem(), CustomOauthProviderArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CustomOauthProviderMapInput)(nil)).Elem(), CustomOauthProviderMap{})
	pulumi.RegisterOutputType(CustomOauthProviderOutput{})
	pulumi.RegisterOutputType(CustomOauthProviderArrayOutput{})
	pulumi.RegisterOutputType(CustomOauthProviderMapOutput{})
}
