version: 2
archives:
  - id: archive
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
    - make tfgen
builds:
  - binary: pulumi-resource-gotrue
    dir: provider
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      - -X github.com/supabase-community/pulumi-gotrue/provider/pkg/version.Version={{.Tag }}
    main: ./cmd/pulumi-resource-gotrue/
changelog:
  disable: true
release:
  disable: false
  prerelease: auto
snapshot:
  version_template: '{{ .Tag }}-SNAPSHOT'
