// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Gotrue
{
    [GotrueResourceType("gotrue:index/customOauthProvider:CustomOauthProvider")]
    public partial class CustomOauthProvider : global::Pulumi.CustomResource
    {
        [Output("acceptableClientIds")]
        public Output<ImmutableArray<string>> AcceptableClientIds { get; private set; } = null!;

        [Output("authorizationParams")]
        public Output<string?> AuthorizationParams { get; private set; } = null!;

        [Output("authorizationUrl")]
        public Output<string?> AuthorizationUrl { get; private set; } = null!;

        [Output("clientId")]
        public Output<string> ClientId { get; private set; } = null!;

        [Output("clientSecret")]
        public Output<string> ClientSecret { get; private set; } = null!;

        [Output("discoveryDocument")]
        public Output<string> DiscoveryDocument { get; private set; } = null!;

        [Output("discoveryUrl")]
        public Output<string?> DiscoveryUrl { get; private set; } = null!;

        [Output("emailOptional")]
        public Output<bool> EmailOptional { get; private set; } = null!;

        [Output("enabled")]
        public Output<bool> Enabled { get; private set; } = null!;

        [Output("identifier")]
        public Output<string> Identifier { get; private set; } = null!;

        [Output("issuer")]
        public Output<string?> Issuer { get; private set; } = null!;

        [Output("jwksUri")]
        public Output<string?> JwksUri { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("pkceEnabled")]
        public Output<bool> PkceEnabled { get; private set; } = null!;

        [Output("providerType")]
        public Output<string> ProviderType { get; private set; } = null!;

        [Output("scopes")]
        public Output<ImmutableArray<string>> Scopes { get; private set; } = null!;

        [Output("skipNonceCheck")]
        public Output<bool> SkipNonceCheck { get; private set; } = null!;

        [Output("tokenUrl")]
        public Output<string?> TokenUrl { get; private set; } = null!;

        [Output("userinfoUrl")]
        public Output<string?> UserinfoUrl { get; private set; } = null!;


        /// <summary>
        /// Create a CustomOauthProvider resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public CustomOauthProvider(string name, CustomOauthProviderArgs args, CustomResourceOptions? options = null)
            : base("gotrue:index/customOauthProvider:CustomOauthProvider", name, args ?? new CustomOauthProviderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private CustomOauthProvider(string name, Input<string> id, CustomOauthProviderState? state = null, CustomResourceOptions? options = null)
            : base("gotrue:index/customOauthProvider:CustomOauthProvider", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/supabase-community/pulumi-gotrue",
                AdditionalSecretOutputs =
                {
                    "clientSecret",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing CustomOauthProvider resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static CustomOauthProvider Get(string name, Input<string> id, CustomOauthProviderState? state = null, CustomResourceOptions? options = null)
        {
            return new CustomOauthProvider(name, id, state, options);
        }
    }

    public sealed class CustomOauthProviderArgs : global::Pulumi.ResourceArgs
    {
        [Input("acceptableClientIds")]
        private InputList<string>? _acceptableClientIds;
        public InputList<string> AcceptableClientIds
        {
            get => _acceptableClientIds ?? (_acceptableClientIds = new InputList<string>());
            set => _acceptableClientIds = value;
        }

        [Input("authorizationParams")]
        public Input<string>? AuthorizationParams { get; set; }

        [Input("authorizationUrl")]
        public Input<string>? AuthorizationUrl { get; set; }

        [Input("clientId", required: true)]
        public Input<string> ClientId { get; set; } = null!;

        [Input("clientSecret", required: true)]
        private Input<string>? _clientSecret;
        public Input<string>? ClientSecret
        {
            get => _clientSecret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _clientSecret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("discoveryUrl")]
        public Input<string>? DiscoveryUrl { get; set; }

        [Input("emailOptional")]
        public Input<bool>? EmailOptional { get; set; }

        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("identifier", required: true)]
        public Input<string> Identifier { get; set; } = null!;

        [Input("issuer")]
        public Input<string>? Issuer { get; set; }

        [Input("jwksUri")]
        public Input<string>? JwksUri { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("pkceEnabled")]
        public Input<bool>? PkceEnabled { get; set; }

        [Input("providerType", required: true)]
        public Input<string> ProviderType { get; set; } = null!;

        [Input("scopes")]
        private InputList<string>? _scopes;
        public InputList<string> Scopes
        {
            get => _scopes ?? (_scopes = new InputList<string>());
            set => _scopes = value;
        }

        [Input("skipNonceCheck")]
        public Input<bool>? SkipNonceCheck { get; set; }

        [Input("tokenUrl")]
        public Input<string>? TokenUrl { get; set; }

        [Input("userinfoUrl")]
        public Input<string>? UserinfoUrl { get; set; }

        public CustomOauthProviderArgs()
        {
        }
        public static new CustomOauthProviderArgs Empty => new CustomOauthProviderArgs();
    }

    public sealed class CustomOauthProviderState : global::Pulumi.ResourceArgs
    {
        [Input("acceptableClientIds")]
        private InputList<string>? _acceptableClientIds;
        public InputList<string> AcceptableClientIds
        {
            get => _acceptableClientIds ?? (_acceptableClientIds = new InputList<string>());
            set => _acceptableClientIds = value;
        }

        [Input("authorizationParams")]
        public Input<string>? AuthorizationParams { get; set; }

        [Input("authorizationUrl")]
        public Input<string>? AuthorizationUrl { get; set; }

        [Input("clientId")]
        public Input<string>? ClientId { get; set; }

        [Input("clientSecret")]
        private Input<string>? _clientSecret;
        public Input<string>? ClientSecret
        {
            get => _clientSecret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _clientSecret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("discoveryDocument")]
        public Input<string>? DiscoveryDocument { get; set; }

        [Input("discoveryUrl")]
        public Input<string>? DiscoveryUrl { get; set; }

        [Input("emailOptional")]
        public Input<bool>? EmailOptional { get; set; }

        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("identifier")]
        public Input<string>? Identifier { get; set; }

        [Input("issuer")]
        public Input<string>? Issuer { get; set; }

        [Input("jwksUri")]
        public Input<string>? JwksUri { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("pkceEnabled")]
        public Input<bool>? PkceEnabled { get; set; }

        [Input("providerType")]
        public Input<string>? ProviderType { get; set; }

        [Input("scopes")]
        private InputList<string>? _scopes;
        public InputList<string> Scopes
        {
            get => _scopes ?? (_scopes = new InputList<string>());
            set => _scopes = value;
        }

        [Input("skipNonceCheck")]
        public Input<bool>? SkipNonceCheck { get; set; }

        [Input("tokenUrl")]
        public Input<string>? TokenUrl { get; set; }

        [Input("userinfoUrl")]
        public Input<string>? UserinfoUrl { get; set; }

        public CustomOauthProviderState()
        {
        }
        public static new CustomOauthProviderState Empty => new CustomOauthProviderState();
    }
}
