// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class CustomOauthProvider extends pulumi.CustomResource {
    /**
     * Get an existing CustomOauthProvider resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CustomOauthProviderState, opts?: pulumi.CustomResourceOptions): CustomOauthProvider {
        return new CustomOauthProvider(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'gotrue:index/customOauthProvider:CustomOauthProvider';

    /**
     * Returns true if the given object is an instance of CustomOauthProvider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CustomOauthProvider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CustomOauthProvider.__pulumiType;
    }

    public readonly acceptableClientIds!: pulumi.Output<string[] | undefined>;
    public readonly attributeMapping!: pulumi.Output<string | undefined>;
    public readonly authorizationParams!: pulumi.Output<string | undefined>;
    public readonly authorizationUrl!: pulumi.Output<string | undefined>;
    public readonly clientId!: pulumi.Output<string>;
    public readonly clientSecret!: pulumi.Output<string>;
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    public /*out*/ readonly discoveryDocument!: pulumi.Output<string>;
    public readonly discoveryUrl!: pulumi.Output<string | undefined>;
    public readonly emailOptional!: pulumi.Output<boolean>;
    public readonly enabled!: pulumi.Output<boolean>;
    public readonly identifier!: pulumi.Output<string>;
    public readonly issuer!: pulumi.Output<string | undefined>;
    public readonly jwksUri!: pulumi.Output<string | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly pkceEnabled!: pulumi.Output<boolean>;
    public readonly providerType!: pulumi.Output<string>;
    public readonly scopes!: pulumi.Output<string[]>;
    public readonly skipNonceCheck!: pulumi.Output<boolean>;
    public readonly tokenUrl!: pulumi.Output<string | undefined>;
    public /*out*/ readonly updatedAt!: pulumi.Output<string>;
    public readonly userinfoUrl!: pulumi.Output<string | undefined>;

    /**
     * Create a CustomOauthProvider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CustomOauthProviderArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CustomOauthProviderArgs | CustomOauthProviderState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CustomOauthProviderState | undefined;
            resourceInputs["acceptableClientIds"] = state ? state.acceptableClientIds : undefined;
            resourceInputs["attributeMapping"] = state ? state.attributeMapping : undefined;
            resourceInputs["authorizationParams"] = state ? state.authorizationParams : undefined;
            resourceInputs["authorizationUrl"] = state ? state.authorizationUrl : undefined;
            resourceInputs["clientId"] = state ? state.clientId : undefined;
            resourceInputs["clientSecret"] = state ? state.clientSecret : undefined;
            resourceInputs["createdAt"] = state ? state.createdAt : undefined;
            resourceInputs["discoveryDocument"] = state ? state.discoveryDocument : undefined;
            resourceInputs["discoveryUrl"] = state ? state.discoveryUrl : undefined;
            resourceInputs["emailOptional"] = state ? state.emailOptional : undefined;
            resourceInputs["enabled"] = state ? state.enabled : undefined;
            resourceInputs["identifier"] = state ? state.identifier : undefined;
            resourceInputs["issuer"] = state ? state.issuer : undefined;
            resourceInputs["jwksUri"] = state ? state.jwksUri : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["pkceEnabled"] = state ? state.pkceEnabled : undefined;
            resourceInputs["providerType"] = state ? state.providerType : undefined;
            resourceInputs["scopes"] = state ? state.scopes : undefined;
            resourceInputs["skipNonceCheck"] = state ? state.skipNonceCheck : undefined;
            resourceInputs["tokenUrl"] = state ? state.tokenUrl : undefined;
            resourceInputs["updatedAt"] = state ? state.updatedAt : undefined;
            resourceInputs["userinfoUrl"] = state ? state.userinfoUrl : undefined;
        } else {
            const args = argsOrState as CustomOauthProviderArgs | undefined;
            if ((!args || args.clientId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'clientId'");
            }
            if ((!args || args.clientSecret === undefined) && !opts.urn) {
                throw new Error("Missing required property 'clientSecret'");
            }
            if ((!args || args.identifier === undefined) && !opts.urn) {
                throw new Error("Missing required property 'identifier'");
            }
            if ((!args || args.providerType === undefined) && !opts.urn) {
                throw new Error("Missing required property 'providerType'");
            }
            resourceInputs["acceptableClientIds"] = args ? args.acceptableClientIds : undefined;
            resourceInputs["attributeMapping"] = args ? args.attributeMapping : undefined;
            resourceInputs["authorizationParams"] = args ? args.authorizationParams : undefined;
            resourceInputs["authorizationUrl"] = args ? args.authorizationUrl : undefined;
            resourceInputs["clientId"] = args ? args.clientId : undefined;
            resourceInputs["clientSecret"] = args?.clientSecret ? pulumi.secret(args.clientSecret) : undefined;
            resourceInputs["discoveryUrl"] = args ? args.discoveryUrl : undefined;
            resourceInputs["emailOptional"] = args ? args.emailOptional : undefined;
            resourceInputs["enabled"] = args ? args.enabled : undefined;
            resourceInputs["identifier"] = args ? args.identifier : undefined;
            resourceInputs["issuer"] = args ? args.issuer : undefined;
            resourceInputs["jwksUri"] = args ? args.jwksUri : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["pkceEnabled"] = args ? args.pkceEnabled : undefined;
            resourceInputs["providerType"] = args ? args.providerType : undefined;
            resourceInputs["scopes"] = args ? args.scopes : undefined;
            resourceInputs["skipNonceCheck"] = args ? args.skipNonceCheck : undefined;
            resourceInputs["tokenUrl"] = args ? args.tokenUrl : undefined;
            resourceInputs["userinfoUrl"] = args ? args.userinfoUrl : undefined;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["discoveryDocument"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["clientSecret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(CustomOauthProvider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering CustomOauthProvider resources.
 */
export interface CustomOauthProviderState {
    acceptableClientIds?: pulumi.Input<pulumi.Input<string>[]>;
    attributeMapping?: pulumi.Input<string>;
    authorizationParams?: pulumi.Input<string>;
    authorizationUrl?: pulumi.Input<string>;
    clientId?: pulumi.Input<string>;
    clientSecret?: pulumi.Input<string>;
    createdAt?: pulumi.Input<string>;
    discoveryDocument?: pulumi.Input<string>;
    discoveryUrl?: pulumi.Input<string>;
    emailOptional?: pulumi.Input<boolean>;
    enabled?: pulumi.Input<boolean>;
    identifier?: pulumi.Input<string>;
    issuer?: pulumi.Input<string>;
    jwksUri?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    pkceEnabled?: pulumi.Input<boolean>;
    providerType?: pulumi.Input<string>;
    scopes?: pulumi.Input<pulumi.Input<string>[]>;
    skipNonceCheck?: pulumi.Input<boolean>;
    tokenUrl?: pulumi.Input<string>;
    updatedAt?: pulumi.Input<string>;
    userinfoUrl?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a CustomOauthProvider resource.
 */
export interface CustomOauthProviderArgs {
    acceptableClientIds?: pulumi.Input<pulumi.Input<string>[]>;
    attributeMapping?: pulumi.Input<string>;
    authorizationParams?: pulumi.Input<string>;
    authorizationUrl?: pulumi.Input<string>;
    clientId: pulumi.Input<string>;
    clientSecret: pulumi.Input<string>;
    discoveryUrl?: pulumi.Input<string>;
    emailOptional?: pulumi.Input<boolean>;
    enabled?: pulumi.Input<boolean>;
    identifier: pulumi.Input<string>;
    issuer?: pulumi.Input<string>;
    jwksUri?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    pkceEnabled?: pulumi.Input<boolean>;
    providerType: pulumi.Input<string>;
    scopes?: pulumi.Input<pulumi.Input<string>[]>;
    skipNonceCheck?: pulumi.Input<boolean>;
    tokenUrl?: pulumi.Input<string>;
    userinfoUrl?: pulumi.Input<string>;
}
