// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SamlIdentityProvider extends pulumi.CustomResource {
    /**
     * Get an existing SamlIdentityProvider resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SamlIdentityProviderState, opts?: pulumi.CustomResourceOptions): SamlIdentityProvider {
        return new SamlIdentityProvider(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'gotrue:index/samlIdentityProvider:SamlIdentityProvider';

    /**
     * Returns true if the given object is an instance of SamlIdentityProvider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SamlIdentityProvider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SamlIdentityProvider.__pulumiType;
    }

    public readonly attributeMapping!: pulumi.Output<string | undefined>;
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    public readonly domains!: pulumi.Output<string[] | undefined>;
    public readonly metadataUrl!: pulumi.Output<string | undefined>;
    public readonly metadataXml!: pulumi.Output<string | undefined>;
    public /*out*/ readonly updatedAt!: pulumi.Output<string>;

    /**
     * Create a SamlIdentityProvider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: SamlIdentityProviderArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SamlIdentityProviderArgs | SamlIdentityProviderState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SamlIdentityProviderState | undefined;
            resourceInputs["attributeMapping"] = state ? state.attributeMapping : undefined;
            resourceInputs["createdAt"] = state ? state.createdAt : undefined;
            resourceInputs["domains"] = state ? state.domains : undefined;
            resourceInputs["metadataUrl"] = state ? state.metadataUrl : undefined;
            resourceInputs["metadataXml"] = state ? state.metadataXml : undefined;
            resourceInputs["updatedAt"] = state ? state.updatedAt : undefined;
        } else {
            const args = argsOrState as SamlIdentityProviderArgs | undefined;
            resourceInputs["attributeMapping"] = args ? args.attributeMapping : undefined;
            resourceInputs["domains"] = args ? args.domains : undefined;
            resourceInputs["metadataUrl"] = args ? args.metadataUrl : undefined;
            resourceInputs["metadataXml"] = args ? args.metadataXml : undefined;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SamlIdentityProvider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SamlIdentityProvider resources.
 */
export interface SamlIdentityProviderState {
    attributeMapping?: pulumi.Input<string>;
    createdAt?: pulumi.Input<string>;
    domains?: pulumi.Input<pulumi.Input<string>[]>;
    metadataUrl?: pulumi.Input<string>;
    metadataXml?: pulumi.Input<string>;
    updatedAt?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SamlIdentityProvider resource.
 */
export interface SamlIdentityProviderArgs {
    attributeMapping?: pulumi.Input<string>;
    domains?: pulumi.Input<pulumi.Input<string>[]>;
    metadataUrl?: pulumi.Input<string>;
    metadataXml?: pulumi.Input<string>;
}
