# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .saml_identity_provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_gotrue.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_gotrue.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "gotrue",
  "mod": "index/samlIdentityProvider",
  "fqn": "pulumi_gotrue",
  "classes": {
   "gotrue:index/samlIdentityProvider:SamlIdentityProvider": "SamlIdentityProvider"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "gotrue",
  "token": "pulumi:providers:gotrue",
  "fqn": "pulumi_gotrue",
  "class": "Provider"
 }
]
"""
)
