# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['CustomOauthProviderArgs', 'CustomOauthProvider']

@pulumi.input_type
class CustomOauthProviderArgs:
    def __init__(__self__, *,
                 client_id: pulumi.Input[str],
                 client_secret: pulumi.Input[str],
                 identifier: pulumi.Input[str],
                 provider_type: pulumi.Input[str],
                 acceptable_client_ids: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 authorization_params: Optional[pulumi.Input[str]] = None,
                 authorization_url: Optional[pulumi.Input[str]] = None,
                 discovery_url: Optional[pulumi.Input[str]] = None,
                 email_optional: Optional[pulumi.Input[bool]] = None,
                 enabled: Optional[pulumi.Input[bool]] = None,
                 issuer: Optional[pulumi.Input[str]] = None,
                 jwks_uri: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 pkce_enabled: Optional[pulumi.Input[bool]] = None,
                 scopes: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 skip_nonce_check: Optional[pulumi.Input[bool]] = None,
                 token_url: Optional[pulumi.Input[str]] = None,
                 userinfo_url: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a CustomOauthProvider resource.
        """
        pulumi.set(__self__, "client_id", client_id)
        pulumi.set(__self__, "client_secret", client_secret)
        pulumi.set(__self__, "identifier", identifier)
        pulumi.set(__self__, "provider_type", provider_type)
        if acceptable_client_ids is not None:
            pulumi.set(__self__, "acceptable_client_ids", acceptable_client_ids)
        if authorization_params is not None:
            pulumi.set(__self__, "authorization_params", authorization_params)
        if authorization_url is not None:
            pulumi.set(__self__, "authorization_url", authorization_url)
        if discovery_url is not None:
            pulumi.set(__self__, "discovery_url", discovery_url)
        if email_optional is not None:
            pulumi.set(__self__, "email_optional", email_optional)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if issuer is not None:
            pulumi.set(__self__, "issuer", issuer)
        if jwks_uri is not None:
            pulumi.set(__self__, "jwks_uri", jwks_uri)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if pkce_enabled is not None:
            pulumi.set(__self__, "pkce_enabled", pkce_enabled)
        if scopes is not None:
            pulumi.set(__self__, "scopes", scopes)
        if skip_nonce_check is not None:
            pulumi.set(__self__, "skip_nonce_check", skip_nonce_check)
        if token_url is not None:
            pulumi.set(__self__, "token_url", token_url)
        if userinfo_url is not None:
            pulumi.set(__self__, "userinfo_url", userinfo_url)

    @property
    @pulumi.getter(name="clientId")
    def client_id(self) -> pulumi.Input[str]:
        return pulumi.get(self, "client_id")

    @client_id.setter
    def client_id(self, value: pulumi.Input[str]):
        pulumi.set(self, "client_id", value)

    @property
    @pulumi.getter(name="clientSecret")
    def client_secret(self) -> pulumi.Input[str]:
        return pulumi.get(self, "client_secret")

    @client_secret.setter
    def client_secret(self, value: pulumi.Input[str]):
        pulumi.set(self, "client_secret", value)

    @property
    @pulumi.getter
    def identifier(self) -> pulumi.Input[str]:
        return pulumi.get(self, "identifier")

    @identifier.setter
    def identifier(self, value: pulumi.Input[str]):
        pulumi.set(self, "identifier", value)

    @property
    @pulumi.getter(name="providerType")
    def provider_type(self) -> pulumi.Input[str]:
        return pulumi.get(self, "provider_type")

    @provider_type.setter
    def provider_type(self, value: pulumi.Input[str]):
        pulumi.set(self, "provider_type", value)

    @property
    @pulumi.getter(name="acceptableClientIds")
    def acceptable_client_ids(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]:
        return pulumi.get(self, "acceptable_client_ids")

    @acceptable_client_ids.setter
    def acceptable_client_ids(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]):
        pulumi.set(self, "acceptable_client_ids", value)

    @property
    @pulumi.getter(name="authorizationParams")
    def authorization_params(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "authorization_params")

    @authorization_params.setter
    def authorization_params(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "authorization_params", value)

    @property
    @pulumi.getter(name="authorizationUrl")
    def authorization_url(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "authorization_url")

    @authorization_url.setter
    def authorization_url(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "authorization_url", value)

    @property
    @pulumi.getter(name="discoveryUrl")
    def discovery_url(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "discovery_url")

    @discovery_url.setter
    def discovery_url(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "discovery_url", value)

    @property
    @pulumi.getter(name="emailOptional")
    def email_optional(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "email_optional")

    @email_optional.setter
    def email_optional(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "email_optional", value)

    @property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "enabled", value)

    @property
    @pulumi.getter
    def issuer(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "issuer")

    @issuer.setter
    def issuer(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "issuer", value)

    @property
    @pulumi.getter(name="jwksUri")
    def jwks_uri(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "jwks_uri")

    @jwks_uri.setter
    def jwks_uri(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "jwks_uri", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="pkceEnabled")
    def pkce_enabled(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "pkce_enabled")

    @pkce_enabled.setter
    def pkce_enabled(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "pkce_enabled", value)

    @property
    @pulumi.getter
    def scopes(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]:
        return pulumi.get(self, "scopes")

    @scopes.setter
    def scopes(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]):
        pulumi.set(self, "scopes", value)

    @property
    @pulumi.getter(name="skipNonceCheck")
    def skip_nonce_check(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "skip_nonce_check")

    @skip_nonce_check.setter
    def skip_nonce_check(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "skip_nonce_check", value)

    @property
    @pulumi.getter(name="tokenUrl")
    def token_url(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "token_url")

    @token_url.setter
    def token_url(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "token_url", value)

    @property
    @pulumi.getter(name="userinfoUrl")
    def userinfo_url(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "userinfo_url")

    @userinfo_url.setter
    def userinfo_url(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "userinfo_url", value)


@pulumi.input_type
class _CustomOauthProviderState:
    def __init__(__self__, *,
                 acceptable_client_ids: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 authorization_params: Optional[pulumi.Input[str]] = None,
                 authorization_url: Optional[pulumi.Input[str]] = None,
                 client_id: Optional[pulumi.Input[str]] = None,
                 client_secret: Optional[pulumi.Input[str]] = None,
                 discovery_document: Optional[pulumi.Input[str]] = None,
                 discovery_url: Optional[pulumi.Input[str]] = None,
                 email_optional: Optional[pulumi.Input[bool]] = None,
                 enabled: Optional[pulumi.Input[bool]] = None,
                 identifier: Optional[pulumi.Input[str]] = None,
                 issuer: Optional[pulumi.Input[str]] = None,
                 jwks_uri: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 pkce_enabled: Optional[pulumi.Input[bool]] = None,
                 provider_type: Optional[pulumi.Input[str]] = None,
                 scopes: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 skip_nonce_check: Optional[pulumi.Input[bool]] = None,
                 token_url: Optional[pulumi.Input[str]] = None,
                 userinfo_url: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering CustomOauthProvider resources.
        """
        if acceptable_client_ids is not None:
            pulumi.set(__self__, "acceptable_client_ids", acceptable_client_ids)
        if authorization_params is not None:
            pulumi.set(__self__, "authorization_params", authorization_params)
        if authorization_url is not None:
            pulumi.set(__self__, "authorization_url", authorization_url)
        if client_id is not None:
            pulumi.set(__self__, "client_id", client_id)
        if client_secret is not None:
            pulumi.set(__self__, "client_secret", client_secret)
        if discovery_document is not None:
            pulumi.set(__self__, "discovery_document", discovery_document)
        if discovery_url is not None:
            pulumi.set(__self__, "discovery_url", discovery_url)
        if email_optional is not None:
            pulumi.set(__self__, "email_optional", email_optional)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if identifier is not None:
            pulumi.set(__self__, "identifier", identifier)
        if issuer is not None:
            pulumi.set(__self__, "issuer", issuer)
        if jwks_uri is not None:
            pulumi.set(__self__, "jwks_uri", jwks_uri)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if pkce_enabled is not None:
            pulumi.set(__self__, "pkce_enabled", pkce_enabled)
        if provider_type is not None:
            pulumi.set(__self__, "provider_type", provider_type)
        if scopes is not None:
            pulumi.set(__self__, "scopes", scopes)
        if skip_nonce_check is not None:
            pulumi.set(__self__, "skip_nonce_check", skip_nonce_check)
        if token_url is not None:
            pulumi.set(__self__, "token_url", token_url)
        if userinfo_url is not None:
            pulumi.set(__self__, "userinfo_url", userinfo_url)

    @property
    @pulumi.getter(name="acceptableClientIds")
    def acceptable_client_ids(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]:
        return pulumi.get(self, "acceptable_client_ids")

    @acceptable_client_ids.setter
    def acceptable_client_ids(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]):
        pulumi.set(self, "acceptable_client_ids", value)

    @property
    @pulumi.getter(name="authorizationParams")
    def authorization_params(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "authorization_params")

    @authorization_params.setter
    def authorization_params(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "authorization_params", value)

    @property
    @pulumi.getter(name="authorizationUrl")
    def authorization_url(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "authorization_url")

    @authorization_url.setter
    def authorization_url(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "authorization_url", value)

    @property
    @pulumi.getter(name="clientId")
    def client_id(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "client_id")

    @client_id.setter
    def client_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "client_id", value)

    @property
    @pulumi.getter(name="clientSecret")
    def client_secret(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "client_secret")

    @client_secret.setter
    def client_secret(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "client_secret", value)

    @property
    @pulumi.getter(name="discoveryDocument")
    def discovery_document(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "discovery_document")

    @discovery_document.setter
    def discovery_document(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "discovery_document", value)

    @property
    @pulumi.getter(name="discoveryUrl")
    def discovery_url(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "discovery_url")

    @discovery_url.setter
    def discovery_url(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "discovery_url", value)

    @property
    @pulumi.getter(name="emailOptional")
    def email_optional(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "email_optional")

    @email_optional.setter
    def email_optional(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "email_optional", value)

    @property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "enabled", value)

    @property
    @pulumi.getter
    def identifier(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "identifier")

    @identifier.setter
    def identifier(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "identifier", value)

    @property
    @pulumi.getter
    def issuer(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "issuer")

    @issuer.setter
    def issuer(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "issuer", value)

    @property
    @pulumi.getter(name="jwksUri")
    def jwks_uri(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "jwks_uri")

    @jwks_uri.setter
    def jwks_uri(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "jwks_uri", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="pkceEnabled")
    def pkce_enabled(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "pkce_enabled")

    @pkce_enabled.setter
    def pkce_enabled(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "pkce_enabled", value)

    @property
    @pulumi.getter(name="providerType")
    def provider_type(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "provider_type")

    @provider_type.setter
    def provider_type(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "provider_type", value)

    @property
    @pulumi.getter
    def scopes(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]:
        return pulumi.get(self, "scopes")

    @scopes.setter
    def scopes(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]):
        pulumi.set(self, "scopes", value)

    @property
    @pulumi.getter(name="skipNonceCheck")
    def skip_nonce_check(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "skip_nonce_check")

    @skip_nonce_check.setter
    def skip_nonce_check(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "skip_nonce_check", value)

    @property
    @pulumi.getter(name="tokenUrl")
    def token_url(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "token_url")

    @token_url.setter
    def token_url(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "token_url", value)

    @property
    @pulumi.getter(name="userinfoUrl")
    def userinfo_url(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "userinfo_url")

    @userinfo_url.setter
    def userinfo_url(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "userinfo_url", value)


class CustomOauthProvider(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 acceptable_client_ids: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 authorization_params: Optional[pulumi.Input[str]] = None,
                 authorization_url: Optional[pulumi.Input[str]] = None,
                 client_id: Optional[pulumi.Input[str]] = None,
                 client_secret: Optional[pulumi.Input[str]] = None,
                 discovery_url: Optional[pulumi.Input[str]] = None,
                 email_optional: Optional[pulumi.Input[bool]] = None,
                 enabled: Optional[pulumi.Input[bool]] = None,
                 identifier: Optional[pulumi.Input[str]] = None,
                 issuer: Optional[pulumi.Input[str]] = None,
                 jwks_uri: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 pkce_enabled: Optional[pulumi.Input[bool]] = None,
                 provider_type: Optional[pulumi.Input[str]] = None,
                 scopes: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 skip_nonce_check: Optional[pulumi.Input[bool]] = None,
                 token_url: Optional[pulumi.Input[str]] = None,
                 userinfo_url: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Create a CustomOauthProvider resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: CustomOauthProviderArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a CustomOauthProvider resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param CustomOauthProviderArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(CustomOauthProviderArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 acceptable_client_ids: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 authorization_params: Optional[pulumi.Input[str]] = None,
                 authorization_url: Optional[pulumi.Input[str]] = None,
                 client_id: Optional[pulumi.Input[str]] = None,
                 client_secret: Optional[pulumi.Input[str]] = None,
                 discovery_url: Optional[pulumi.Input[str]] = None,
                 email_optional: Optional[pulumi.Input[bool]] = None,
                 enabled: Optional[pulumi.Input[bool]] = None,
                 identifier: Optional[pulumi.Input[str]] = None,
                 issuer: Optional[pulumi.Input[str]] = None,
                 jwks_uri: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 pkce_enabled: Optional[pulumi.Input[bool]] = None,
                 provider_type: Optional[pulumi.Input[str]] = None,
                 scopes: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 skip_nonce_check: Optional[pulumi.Input[bool]] = None,
                 token_url: Optional[pulumi.Input[str]] = None,
                 userinfo_url: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = CustomOauthProviderArgs.__new__(CustomOauthProviderArgs)

            __props__.__dict__["acceptable_client_ids"] = acceptable_client_ids
            __props__.__dict__["authorization_params"] = authorization_params
            __props__.__dict__["authorization_url"] = authorization_url
            if client_id is None and not opts.urn:
                raise TypeError("Missing required property 'client_id'")
            __props__.__dict__["client_id"] = client_id
            if client_secret is None and not opts.urn:
                raise TypeError("Missing required property 'client_secret'")
            __props__.__dict__["client_secret"] = None if client_secret is None else pulumi.Output.secret(client_secret)
            __props__.__dict__["discovery_url"] = discovery_url
            __props__.__dict__["email_optional"] = email_optional
            __props__.__dict__["enabled"] = enabled
            if identifier is None and not opts.urn:
                raise TypeError("Missing required property 'identifier'")
            __props__.__dict__["identifier"] = identifier
            __props__.__dict__["issuer"] = issuer
            __props__.__dict__["jwks_uri"] = jwks_uri
            __props__.__dict__["name"] = name
            __props__.__dict__["pkce_enabled"] = pkce_enabled
            if provider_type is None and not opts.urn:
                raise TypeError("Missing required property 'provider_type'")
            __props__.__dict__["provider_type"] = provider_type
            __props__.__dict__["scopes"] = scopes
            __props__.__dict__["skip_nonce_check"] = skip_nonce_check
            __props__.__dict__["token_url"] = token_url
            __props__.__dict__["userinfo_url"] = userinfo_url
            __props__.__dict__["discovery_document"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["clientSecret"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(CustomOauthProvider, __self__).__init__(
            'gotrue:index/customOauthProvider:CustomOauthProvider',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            acceptable_client_ids: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
            authorization_params: Optional[pulumi.Input[str]] = None,
            authorization_url: Optional[pulumi.Input[str]] = None,
            client_id: Optional[pulumi.Input[str]] = None,
            client_secret: Optional[pulumi.Input[str]] = None,
            discovery_document: Optional[pulumi.Input[str]] = None,
            discovery_url: Optional[pulumi.Input[str]] = None,
            email_optional: Optional[pulumi.Input[bool]] = None,
            enabled: Optional[pulumi.Input[bool]] = None,
            identifier: Optional[pulumi.Input[str]] = None,
            issuer: Optional[pulumi.Input[str]] = None,
            jwks_uri: Optional[pulumi.Input[str]] = None,
            name: Optional[pulumi.Input[str]] = None,
            pkce_enabled: Optional[pulumi.Input[bool]] = None,
            provider_type: Optional[pulumi.Input[str]] = None,
            scopes: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
            skip_nonce_check: Optional[pulumi.Input[bool]] = None,
            token_url: Optional[pulumi.Input[str]] = None,
            userinfo_url: Optional[pulumi.Input[str]] = None) -> 'CustomOauthProvider':
        """
        Get an existing CustomOauthProvider resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _CustomOauthProviderState.__new__(_CustomOauthProviderState)

        __props__.__dict__["acceptable_client_ids"] = acceptable_client_ids
        __props__.__dict__["authorization_params"] = authorization_params
        __props__.__dict__["authorization_url"] = authorization_url
        __props__.__dict__["client_id"] = client_id
        __props__.__dict__["client_secret"] = client_secret
        __props__.__dict__["discovery_document"] = discovery_document
        __props__.__dict__["discovery_url"] = discovery_url
        __props__.__dict__["email_optional"] = email_optional
        __props__.__dict__["enabled"] = enabled
        __props__.__dict__["identifier"] = identifier
        __props__.__dict__["issuer"] = issuer
        __props__.__dict__["jwks_uri"] = jwks_uri
        __props__.__dict__["name"] = name
        __props__.__dict__["pkce_enabled"] = pkce_enabled
        __props__.__dict__["provider_type"] = provider_type
        __props__.__dict__["scopes"] = scopes
        __props__.__dict__["skip_nonce_check"] = skip_nonce_check
        __props__.__dict__["token_url"] = token_url
        __props__.__dict__["userinfo_url"] = userinfo_url
        return CustomOauthProvider(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="acceptableClientIds")
    def acceptable_client_ids(self) -> pulumi.Output[Optional[Sequence[str]]]:
        return pulumi.get(self, "acceptable_client_ids")

    @property
    @pulumi.getter(name="authorizationParams")
    def authorization_params(self) -> pulumi.Output[Optional[str]]:
        return pulumi.get(self, "authorization_params")

    @property
    @pulumi.getter(name="authorizationUrl")
    def authorization_url(self) -> pulumi.Output[Optional[str]]:
        return pulumi.get(self, "authorization_url")

    @property
    @pulumi.getter(name="clientId")
    def client_id(self) -> pulumi.Output[str]:
        return pulumi.get(self, "client_id")

    @property
    @pulumi.getter(name="clientSecret")
    def client_secret(self) -> pulumi.Output[str]:
        return pulumi.get(self, "client_secret")

    @property
    @pulumi.getter(name="discoveryDocument")
    def discovery_document(self) -> pulumi.Output[str]:
        return pulumi.get(self, "discovery_document")

    @property
    @pulumi.getter(name="discoveryUrl")
    def discovery_url(self) -> pulumi.Output[Optional[str]]:
        return pulumi.get(self, "discovery_url")

    @property
    @pulumi.getter(name="emailOptional")
    def email_optional(self) -> pulumi.Output[bool]:
        return pulumi.get(self, "email_optional")

    @property
    @pulumi.getter
    def enabled(self) -> pulumi.Output[bool]:
        return pulumi.get(self, "enabled")

    @property
    @pulumi.getter
    def identifier(self) -> pulumi.Output[str]:
        return pulumi.get(self, "identifier")

    @property
    @pulumi.getter
    def issuer(self) -> pulumi.Output[Optional[str]]:
        return pulumi.get(self, "issuer")

    @property
    @pulumi.getter(name="jwksUri")
    def jwks_uri(self) -> pulumi.Output[Optional[str]]:
        return pulumi.get(self, "jwks_uri")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        return pulumi.get(self, "name")

    @property
    @pulumi.getter(name="pkceEnabled")
    def pkce_enabled(self) -> pulumi.Output[bool]:
        return pulumi.get(self, "pkce_enabled")

    @property
    @pulumi.getter(name="providerType")
    def provider_type(self) -> pulumi.Output[str]:
        return pulumi.get(self, "provider_type")

    @property
    @pulumi.getter
    def scopes(self) -> pulumi.Output[Sequence[str]]:
        return pulumi.get(self, "scopes")

    @property
    @pulumi.getter(name="skipNonceCheck")
    def skip_nonce_check(self) -> pulumi.Output[bool]:
        return pulumi.get(self, "skip_nonce_check")

    @property
    @pulumi.getter(name="tokenUrl")
    def token_url(self) -> pulumi.Output[Optional[str]]:
        return pulumi.get(self, "token_url")

    @property
    @pulumi.getter(name="userinfoUrl")
    def userinfo_url(self) -> pulumi.Output[Optional[str]]:
        return pulumi.get(self, "userinfo_url")

